spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

versus.jwt.secret=${JWT_SECRET:dev-secret-change-me-please-make-this-very-long-at-least-64-bytes-aaaaaaaa}
versus.seed.enabled=true
